include = ["kde-builder", "kde_builder/**/*.py", "tests/**/*.py", "scripts/gen_zsh_completions.py"]

[lint]
select = [
    "D",
    "E",
    "F401",
    "N",
    "W",
    "TID252",
]

pydocstyle.convention = "google"

# See https://docs.astral.sh/ruff/rules/ for the list of rules
ignore = [
    "D100", # We do not document the modules (python files).
    "D102", # We do not always document methods.
    "D103", # We do not always document functions.
    "D105", # We do not always document magic methods.
    "D107", # We do not always document __init__ methods.
    "D200", # We do not agree that one line docstrings should open and close on the same line, as this makes inconsistent look of them.
    "D203", # Just to be explicit. Already disabled by following google pydocstyle convention. We use D211 rule instead.
    "D212", # We use D213 rule instead.
    "D406", # Just to be explicit. Already disabled by following google pydocstyle convention.
    "D407", # Just to be explicit. Already disabled by following google pydocstyle convention.
    "D413", # Just to be explicit. Already disabled by following google pydocstyle convention.
    "E501", # We use lines longer than "standard".
]

# Enable rules on top of google pydocstyle convention.
extend-select = [
    "D204", # Follow pep257 convention: add blank line after _class_ docstring.
    "D404", # Follow pep257 convention: do not start docstring with "this" word.
]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"
